/* Copyright 2008 (C) Nicira, Inc.
 *
 * This file is part of NOX.
 *
 * NOX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NOX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NOX.  If not, see <http://www.gnu.org/licenses/>.
 */
//-----------------------------------------------------------------------------
//  
//-----------------------------------------------------------------------------
#ifndef SSL_TEST_STR_HH
#define SSL_TEST_STR_HH

namespace vigil
{
static
const char* test_str = 
"    Terry Bisson"
""
"They're Made out of Meat"
""
"'They're made out of meat.'"
"    "
"'Meat?'"
"    "
"'Meat. They're made out of meat.'"
"    "
"'Meat?'"
"    "
"'There's no doubt about it. We picked up several from different parts of"
"    the planet, took them aboard our recon vessels, and probed them all"
"    the way through. They're completely meat.'"
"    "
"'That's impossible. What about the radio signals? The messages to the"
"    stars?'"
"    "
"'They use the radio waves to talk, but the signals don't come from them."
"    The signals come from machines.'"
"    "
"'So who made the machines? That's who we want to contact.'"
"    "
"'They made the machines. That's what I'm trying to tell you. Meat made"
"    the machines.'"
"    "
"'That's ridiculous. How can meat make a machine? You're asking me to"
"    believe in sentient meat.'"
"    "
"'I'm not asking you, I'm telling you. These creatures are the only"
"    sentient race in that sector and they're made out of meat.'"
"    "
"'Maybe they're like the orfolei. You know, a carbon-based intelligence"
"    that goes through a meat stage.'"
"    "
"'Nope. They're born meat and they die meat. We studied them for several"
"    of their life spans, which didn't take long. Do you have any idea"
"    what's the life span of meat?'"
"    "
"'Spare me. Okay, maybe they're only part meat. You know, like the"
"    weddilei. A meat head with an electron plasma brain inside.'"
"    "
"'Nope. We thought of that, since they do have meat heads, like the"
"    weddilei. But I told you, we probed them. They're meat all the way"
"    through.'"
"    "
"'No brain?'"
"    "
"'Oh, there's a brain all right. It's just that the brain is made out of"
"    meat! That's what I've been trying to tell you.'"
"    "
"'So ... what does the thinking?'"
"    "
"'You're not understanding, are you? You're refusing to deal with what"
"    I'm telling you. The brain does the thinking. The meat.'"
"    "
"'Thinking meat! You're asking me to believe in thinking meat!'"
"    "
"'Yes, thinking meat! Conscious meat! Loving meat. Dreaming meat. The"
"    meat is the whole deal! Are you beginning to get the picture or do I"
"    have to start all over?'"
"    "
"'Omigod. You're serious then. They're made out of meat.'"
"    "
"'Thank you. Finally. Yes. They are indeed made out of meat. And they've"
"    been trying to get in touch with us for almost a hundred of their"
"    years.'"
"    "
"'Omigod. So what does this meat have in mind?'"
"    "
"'First it wants to talk to us. Then I imagine it wants to explore the"
"Universe, contact other sentiences, swap ideas and information. The"
"usual.'"
""
"'We're supposed to talk to meat.'"
"    "
"'That's the idea. That's the message they're sending out by radio."
"    'Hello. Anyone out there. Anybody home.' That sort of thing.'"
"    "
"'They actually do talk, then. They use words, ideas, concepts?'"
"    "
"'Oh, yes. Except they do it with meat.'"
"    "
"'I thought you just told me they used radio.'"
"    "
"'They do, but what do you think is on the radio? Meat sounds. You know"
"    how when you slap or flap meat, it makes a noise? They talk by"
"    flapping their meat at each other. They can even sing by squirting"
"    air through their meat.'"
"    "
"'Omigod. Singing meat. This is altogether too much. So what do you"
"    advise?'"
"    "
"'Officially or unofficially?'"
"    "
"'Both.'"
"    "
"'Officially, we are required to contact, welcome and log in any and all"
"    sentient races or multibeings in this quadrant of the Universe,"
"             without prejudice, fear or favor. Unofficially, I advise"
"                 that we erase the records and forget the whole thing.'"
"    "
"'I was hoping you would say that.'"
"    "
"'It seems harsh, but there is a limit. Do we really want to make contact"
"    with meat?'"
"    "
"'I agree one hundred percent. What's there to say? 'Hello, meat. How's"
"    it going?' But will this work? How many planets are we dealing with"
"    here?'"
"    "
"'Just one. They can travel to other planets in special meat containers,"
"    but they can't live on them. And being meat, they can only travel"
"        through C space. Which limits them to the speed of light and"
"        makes the possibility of their ever making contact pretty slim."
"        Infinitesimal, in fact.'"
"    "
"'So we just pretend there's no one home in the Universe.'"
"    "
"'That's it.'"
"    "
"'Cruel. But you said it yourself, who wants to meet meat? And the ones"
"    who have been aboard our vessels, the ones you probed? You're sure"
"    they won't remember?'"
"    "
"'They'll be considered crackpots if they do. We went into their heads"
"    and smoothed out their meat so that we're just a dream to them.'"
"    "
"'A dream to meat! How strangely appropriate, that we should be meat's"
"    dream.'"
"    "
"'And we marked the entire sector unoccupied.'"
"    "
"'Good. Agreed, officially and unofficially. Case closed. Any others?"
"    Anyone interesting on that side of the galaxy?'"
"    "
"'Yes, a rather shy but sweet hydrogen core cluster intelligence in a"
"    class nine star in G445 zone. Was in contact two galactic rotations"
"    ago, wants to be friendly again.'"
"    "
"'They always come around.'"
"    "
"'And why not? Imagine how unbearably, how unutterably cold the Universe"
"    would be if one were all alone ...'"
"    "
""
"the end ";


}
#endif  // SSL_TEST_STR_HH
