#!/bin/bash

if [ "$EUID" != "0" ]; then
  echo "You must be root to run this script. Sorry, dude!"
  exit 1
fi

LXCDIR=/var/lib/lxc
RF_HOME=..
LOG_FILE=/var/log/rftest1.log

export PATH=$PATH:/usr/local/bin:/usr/local/sbin
cd $RF_HOME &> $LOG_FILE

# Always try to start OVS
ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
	                 --remote=db:Open_vSwitch,manager_options \
	                 --private-key=db:SSL,private_key \
	                 --certificate=db:SSL,certificate \
	                 --bootstrap-ca-cert=db:SSL,ca_cert \
	                 --pidfile --detach &>> $LOG_FILE
ovs-vswitchd --pidfile --detach	&>> $LOG_FILE

echo "Resetting and stopping LXC VMs..."
rm -f $LXCDIR/{rfvm1,b1,b2}/rootfs/var/run/network/ifstate &>> $LOG_FILE
lxc-stop -n b2 &>> $LOG_FILE
lxc-stop -n b1 &>> $LOG_FILE
lxc-stop -n rfvm1 &>> $LOG_FILE

echo "Stopping any running instances and data of rfserver, POX, OVS and MongoDB..."
pkill -15 rfserver &> /dev/null
pkill -15 lt-nox_core &> /dev/null
pkill -15 mongod &> /dev/null
rm -r $HOME/db &>> $LOG_FILE
rm -r /var/lib/lxc/rfvm1/rootfs/opt/rfclient

sudo ovs-vsctl del-br br0
sudo ovs-vsctl del-br dp0
sudo ovs-vsctl del-br switch1
sudo ovs-vsctl emer-reset

if [ "$1" != "clear" ]; then
    echo "Starting MongoDB..."
    mkdir $HOME/db &>> $LOG_FILE
    mongod --quiet --dbpath $HOME/db --logpath /dev/null &
    sleep 5

    echo "Starting the rfvm1 virtual machine..."
    mkdir /var/lib/lxc/rfvm1/rootfs/opt/rfclient &>> $LOG_FILE
    cp build/rfclient /var/lib/lxc/rfvm1/rootfs/opt/rfclient/rfclient &>> $LOG_FILE
    cp /usr/lib/libmongoclient.a /var/lib/lxc/rfvm1/rootfs/usr/lib &>> $LOG_FILE
    cp /usr/lib/libmongoclient.so /var/lib/lxc/rfvm1/rootfs/usr/lib &>> $LOG_FILE
    
    echo "#!/bin/sh" > /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
    echo "sleep 5" >> /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
    echo "/opt/rfclient/rfclient > /var/log/rfclient.log" >> /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
    chmod +x /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
    
    lxc-start -n rfvm1 -d &>> $LOG_FILE


    echo "Starting the management network (br0)..."
    sleep 5
	ovs-vsctl add-br br0 \
		-- add-port br0 rfvm1.0 &>> $LOG_FILE
    ifconfig br0 up
    ifconfig br0 192.169.1.1

    echo "Starting POX and the RouteFlow network controller..."
    ( cd pox && ./pox.py --no-cli topology openflow.topology rfproxy & &>> $LOG_FILE & )
    sleep 5
    
    echo "Starting the RouteFlow server..."
    build/rfserver &>> $LOG_FILE &
    sleep 3
    
    echo "Starting the control plane network (dp0 OVS)..."
	ovs-vsctl add-br dp0 \
		-- add-port dp0 rfvm1.1 \
		-- add-port dp0 rfvm1.2 &>> $LOG_FILE
	ovs-vsctl set Bridge dp0 other-config:datapath-id=7266767372667673 &>> $LOG_FILE
	ovs-vsctl set-controller dp0 tcp:127.0.0.1:6633
    ifconfig dp0 up &>> $LOG_FILE
    sleep 3
        
    echo "Starting the sample network..."
    lxc-start -n b1 -d &>> $LOG_FILE
    lxc-start -n b2 -d &>> $LOG_FILE
	ovs-vsctl add-br switch1 \
		-- add-port switch1 b1.0 \
		-- add-port switch1 b2.0 &>> $LOG_FILE
	ovs-vsctl set-controller switch1 tcp:127.0.0.1:6633
    ifconfig switch1 up &>> $LOG_FILE
    
    cd - &> /dev/null
    sleep 5
    
    echo "Now we'll open this test's log."
    echo "Try pinging b1 from b2:"
    echo "  $ sudo lxc-console -n b1"
    echo "Login and run:"
    echo "  $ ping 172.31.2.2"
    tail -f $LOG_FILE
fi

exit 0
