MAKEAPPS := rfclient

# We are currently migrating from propagating route entries via fixed
# structures (RouteInfo,FlowMod) to an extensible structure (RouteMod). The
# below CFLAG will enable the RouteMod code.
# CFLAGS += -DROUTEMOD_ENABLED

include ../Make.rules
